# Generated by Django 4.0.2 on 2022-02-02 19:37

from django.db import migrations

def seed(apps, schema_editor):
  Player = apps.get_model('mlb', 'Player')
  Team = apps.get_model('mlb', 'Team')
  braves = Team(name='Atlanta Braves', league='National', location='East', wins=40, losses=30)
  giants = Team(name='San Francisco Giants', league='National', location='West', wins=39, losses=50)
  cubs = Team(name='Chicago Cubs', league='National', location='Central', wins=45, losses=25)
  braves.save()
  giants.save()
  cubs.save()
  Player(team = giants, name='Brandon Belt', age='33', position="1B", injured_list=False).save()
  Player(team = giants, name='Kris Bryant', age='30', position="LF", injured_list=False).save()
  Player(team = giants, name='Kervin Castro', age='22', position="P", injured_list=False).save()
  Player(team = braves, name='Ozzie Albies', age='25', position="2B", injured_list=False).save()
  Player(team = braves, name='Tucker Davidson', age='25', position="P", injured_list=False).save()
  Player(team = braves, name='Ender Inciarte', age='31', position="OF", injured_list=False).save()
  Player(team = cubs, name='Jake Arrieta', age='36', position="RHP", injured_list=False).save()
  Player(team = cubs, name='Craig Kimbrel', age='33', position="RHP", injured_list=False).save()
  Player(team = cubs, name='Jason Heyward', age='32', position="RF", injured_list=False).save()

def fallow(apps, schema_editor):
  Player = apps.get_model('mlb', 'Player')
  Team = apps.get_model('mlb', 'Team')
  Team.objects.app().delete()
  Player.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0001_initial'),
    ]

    operations = [
      migrations.RunPython(seed, fallow)
    ]
