# Generated by Django 4.0.2 on 2022-02-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0002_auto_20220202_1956'),
        ('mlb', '0003_auto_20220203_0036'),
    ]

    operations = [
    ]
