# Generated by Django 4.0.2 on 2022-02-03 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(default='location unavailable', max_length=100)),
                ('number_of_wins', models.PositiveSmallIntegerField(default=0)),
                ('number_of_loses', models.PositiveSmallIntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='sports.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('age', models.PositiveSmallIntegerField(default=18)),
                ('available_for_draft', models.BooleanField(default=True)),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sports.team')),
            ],
        ),
    ]
