# Generated by Django 3.2.12 on 2022-02-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='team_name',
        ),
    ]
