# Generated by Django 3.2.12 on 2022-02-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_api', '0002_rename_team_player_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='conf_championships',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='nba_championships',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
