# Generated by Django 3.2.12 on 2022-02-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_api', '0003_auto_20220203_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='conference',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team_name',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
    ]
