# Generated by Django 4.0.2 on 2022-02-02 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Offense', (('O_QB', 'Quarterback'), ('O_RB', 'Running Back'), ('O_FB', 'Fullback'), ('O_WR', 'Wide Receiver'), ('O_TE', 'Tight End'), ('O_OT', 'Offensive Tackle'), ('O_OG', 'Offensive Guard'), ('O_C', 'Center'))), ('Defense', (('D_NT', 'Nose Tackle'), ('D_DT', 'Defensive Tackle'), ('D_DE', 'Defensive End'), ('D_LB', 'Linebacker'), ('D_CB', 'Cornerback'), ('D_FS', 'Free Safety'), ('D_SS', 'Strong Safety'))), ('Special', (('S_K', 'Kicker'), ('S_P', 'Punter'), ('S_LS', 'Long Snapper'), ('S_H', 'Holder'), ('S_KR', 'Kick Returner'), ('S_PR', 'Punt Returner')))], max_length=4)),
                ('age', models.IntegerField()),
                ('injured_reserve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='nfl_app.team')),
            ],
        ),
    ]
