# Generated by Django 4.0.2 on 2022-02-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_deatheater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='name unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='position unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='special_moves',
            field=models.TextField(default='none'),
        ),
    ]
