# Generated by Django 4.0.2 on 2022-02-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def seed(apps, schema_editor):
        Player = apps.get_model('sportsball', 'Player')
        Team = apps.get_model('sportsball', 'Team')
        birds = Team(name="Birds", location='Brooklyn',
                     conference='East Coast Tournament', wins=23, losses=0)
        birds.save()

        Player(team=birds, name="Carl Dungee",
               position='forward', age=23, injured_list=False).save()

    def fallow(apps, schema_editor):
        Player = apps.get_model('sportsball', 'Player')
        Team = apps.get_model('sportsball', 'Team')
        Team.objects.all().delete()
        Player.objects.all().delete()

    dependencies = [
        ('sportsball', '0002_auto_20220202_2218'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
