# Generated by Django 4.0.2 on 2022-02-06 21:54
# Generated by Django 4.0.2 on 2022-02-06 21:28

from django.db import migrations

def seed(apps, schema_editor):
    Team = apps.get_model('rest', 'Team')
    Player = apps.get_model('rest', 'Player')

    lakers = Team(name='Lakers', location='Los Angeles, CA', conference='Western', win=100, loss=69)
    bulls = Team(name='Bulls', location='Chicago, IL', conference='Eastern', win=150, loss=76)
    nuggets = Team(name='Nuggets', location='Denver, CO', conference='Western', win=222, loss=88)
    lakers.save()
    bulls.save()
    nuggets.save()

    Player(name='lakerplayer1', position='position1', age=22, injured_rlist=True, team=lakers).save()
    Player(name='lakerplayer2', position='position2', age=25, injured_rlist=True, team=lakers).save()
    Player(name='lakerplayer3', position='position3', age=26, injured_rlist=False, team=lakers).save()
    Player(name='bullsplayer1', position='position1', age=23, injured_rlist=True, team=bulls).save()
    Player(name='bullsplayer1', position='position2', age=24, injured_rlist=False, team=bulls).save()
    Player(name='bullsplayer1', position='position3', age=27, injured_rlist=False, team=bulls).save()
    Player(name='nuggetsplayer1', position='position1', age=28, injured_rlist=False, team=nuggets).save()
    Player(name='nuggetsplayer1', position='position2', age=65, injured_rlist=True, team=nuggets).save()
    Player(name='nuggetsplayer1', position='position3', age=100, injured_rlist=True, team=nuggets).save()


def fallow(apps, schema_editor):
    Team = apps.get_model('rest', 'Team')
    Player = apps.get_model('rest', 'Player')
    Team.objects.all().delete()
    Player.objects.all().delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
