# Generated by Django 4.0.2 on 2022-02-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='player',
            name='ir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='Guard', max_length=25),
        ),
    ]
