# Generated by Django 4.0.2 on 2022-02-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_player_age_player_ir_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=10),
        ),
    ]
