# Generated by Django 4.0.2 on 2022-02-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsball', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='injured',
        ),
    ]
