# Generated by Django 4.0.2 on 2022-02-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.CharField(default='Not Given', max_length=10),
        ),
    ]
